const test=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js');
const rules=(changes={})=>({...C.DEFAULT_RULES,...changes});
test('blank rules never imply automatic success',()=>assert.equal(C.check('hello','',rules()).items.length,0));
test('Japanese graphemes',()=>assert.equal(C.graphemes('あいう'),3));
test('combining mark counts once',()=>assert.equal(C.graphemes('か\u3099'),1));
test('family emoji counts once',()=>assert.equal(C.graphemes('👨‍👩‍👧‍👦'),1));
test('flag emoji counts once',()=>assert.equal(C.graphemes('🇯🇵'),1));
test('space and newline exclusions',()=>assert.equal(C.count('あ　い\t\nう',rules()).count,3));
test('spaces can be counted',()=>assert.equal(C.count('あ い\n',rules({ignoreSpaces:false})).count,3));
test('newlines can be counted',()=>assert.equal(C.count('あ\nい',rules({ignoreNewlines:false})).count,3));
test('CRLF is normalized',()=>assert.equal(C.count('あ\r\nい',rules({ignoreNewlines:false})).count,3));
test('Markdown headings excluded explicitly',()=>assert.equal(C.count('# 題\n本文',rules({excludeHeadings:true})).count,2));
test('ordinary text starting hashtag without space stays',()=>assert.equal(C.count('#題\n本文',rules({excludeHeadings:true})).count,4));
test('reference heading excludes remainder',()=>assert.equal(C.count('本文\n## 参考文献\n出典',rules({excludeReferences:true})).count,2));
test('reference term in a sentence is not a heading',()=>assert.equal(C.count('参考文献を読む',rules({excludeReferences:true})).count,7));
test('selected range counts only selection',()=>assert.equal(C.count('abcdef',rules(),{start:1,end:4}).count,3));
test('invalid range safely falls back to full text',()=>assert.equal(C.count('abc',rules(),{start:8,end:9}).count,3));
test('minimum is inclusive',()=>assert.equal(C.check('abc','',rules({min:'3'})).pass,1));
test('maximum is inclusive',()=>assert.equal(C.check('abc','',rules({max:'3'})).pass,1));
test('too short fails',()=>assert.equal(C.check('ab','',rules({min:'3'})).fail,1));
test('too long fails',()=>assert.equal(C.check('abcd','',rules({max:'3'})).fail,1));
test('blank manuscript waits instead of passing maximum',()=>assert.equal(C.check('','',rules({max:'400'})).wait,1));
test('inverted bounds are invalid',()=>assert.ok(C.bounds(rules({min:'5',max:'4'})).error));
test('negative bounds are invalid',()=>assert.ok(C.bounds(rules({min:'-1'})).error));
test('fractional bounds are invalid',()=>assert.ok(C.bounds(rules({max:'1.5'})).error));
test('upper limit enforced',()=>assert.ok(C.bounds(rules({max:'1000001'})).error));
test('required phrases use literal strings, not regex',()=>assert.equal(C.check('abc','',rules({required:'.*'})).fail,1));
test('case-sensitive term matching',()=>assert.equal(C.check('todo','',rules({forbidden:'TODO'})).pass,1));
test('duplicate rule lines deduplicated',()=>assert.deepEqual(C.lines('背景\n背景\n\n提案'),['背景','提案']));
test('required terms inspect full manuscript even when count uses range',()=>assert.equal(C.check('ABC 参考文献','',rules({required:'参考文献'}),{start:0,end:3}).pass,1));
test('file checks wait for a filename',()=>assert.equal(C.check('a','',rules({filenameParts:'ID',extensions:'pdf'})).wait,2));
test('uppercase extension accepted',()=>assert.equal(C.check('a','ID.PDF',rules({filenameParts:'ID',extensions:'.pdf, docx'})).pass,2));
test('misleading suffix fails',()=>assert.equal(C.check('a','report.pdf.exe',rules({extensions:'pdf'})).fail,1));
test('invalid extension setting fails',()=>assert.equal(C.check('a','report.pdf',rules({extensions:'p*d*f'})).fail,1));
test('rules export excludes manuscript and filename',()=>assert.deepEqual(Object.keys(C.rulePack(rules())),['app','version','type','rules']));
test('wrong schema rejected',()=>assert.throws(()=>C.validatePack({app:'other',version:1})));
test('wrong boolean type rejected',()=>assert.throws(()=>C.normalizeRules({ignoreSpaces:'false'})));
test('overlarge condition list rejected',()=>assert.throws(()=>C.normalizeRules({required:Array.from({length:101},(_,i)=>'a'+i).join('\n')})));
test('backup round trip',()=>{const p={app:'teishutsu-guard',version:1,type:'backup',rules:rules(),text:'abc',filename:'a.txt',range:{start:0,end:2}};assert.deepEqual(C.validatePack(p),p);});
test('out-of-bounds backup selection rejected',()=>assert.throws(()=>C.validatePack({app:'teishutsu-guard',version:1,type:'backup',rules:rules(),text:'a',filename:'',range:{start:0,end:3}})));
test('normalization ignores unknown properties',()=>assert.equal(C.normalizeRules({unexpected:'x'}).unexpected,undefined));
